// Field Names: 
// ID	NAME	Carto_ID	Carto_ID	Policies_Count	Just_Evict	Rent_Control	Rent_Mediation	Mobile_Home	Mobile_Home	Grad_Density	MU_Zone	Condo_Conv	Form_Based	Housing_Overlay_Year	Loc_Density	Incl_Housing	In_Lieu	Home_Rehab	Res_Fee	Comm_Fee	Buyer_Assist	Foreclose_Assist	Comm_Trust	Aff_Fund

var inventoryText = 
[["0","Agoura Hills","62","62","5","No","No","No","No","No","No","Allows for Mixed-Use projects, est. 2014","Yes - Tenant notice, relocation assistance, inclusionary housing requirements apply, anti-discrimination policies, est. 2011","No","No","No","Yes (9133.5), est. 1987","Yes (9133.6), est. 1987","Yes, est. 2008","No","No","No","No","No","No"],
["1","Alhambra","71","71","3","No","No","No","No","Housing Element speaks to allowing SROs in R3","No","Yes (in CBD zone), est. 2013","No","No","No","No","No","No","Yes, est. 2014","No","No","Yes, est. 2012","No","No","No"],
["2","Arcadia","48","48","2","No","No","No","No","No","No","Yes, est. 2010","No","No","No","Yes, est. 2010","No","No","No","No","No","No","No","No","No"],
["3","Artesia","66","66","1","No","No","No","No","No","No","No","No","No","No","No","No","No","Yes, est. 2013","No","No","No","No","No","No"],
["4","Azusa","73","73","3","No","No","No","Yes, est. 1992","No","No","Yes, est. 2006","No","No","No","No","No","No","Yes, est. 1992","No","No","No","No","No","No"],
["5","Baldwin Park","40","40","3","No","No","No","No","No","No","Yes, est. 2011","No","No","No","No","No","No","Yes, est. 2014","No","No","Yes, updated 2013","No","No","No"],
["6","Bell","49","49","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["7","Bell Gardens","82","82","1","No","No","No","No","No","No","Yes, est. 2007","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["8","Bellflower","54","54","2","No","No","No","No","No","No","No","No","No","No","No","No","No","Yes, est. 2013","No","No","Yes, est. 2013","No","No","No"],
["9","Beverly Hills","61","61","7","Yes (4.5.502-508), est. 1979","Yes (4.5.303), est. 1978","No","No","No","No","Yes, est. 2003","Yes, tenant notice, relocation, first purchase annual limit (10.2.710, 711, 712), est. 1989","No","Yes, est. 2012","Yes (10-3.15.2), est. 2013","Mentioned in Housing Element for future","No, Mentioned in Housing Element for future","Yes, est. 1992","No","No","No","No","No","No"],
["10","Bradbury","19","19","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["11","Burbank","88","88","3","No","No","No","No","No","No","Allows for Mixed-Use projects, est. 1997","Yes, Administrative Use Permit, Compliance with current regulations, 180 days written notice, first right of purchase, relocation assistance., est. 1986","No","No","No","No","No","Yes, est. 2002","No","No","No","No","No","No"],
["12","Calabasas","35","35","9","No","No","No","Yes, est. 2004","No","No","Yes, est. 2010","Yes - Relocation Assistance, vacancy rate 4%, est. 2010","No","No","No","Yes, est. 1998","Yes, est. 2006","Yes, est. 2014","No","Yes, est. 2006","Yes, est. 2008","No","No","Yes, est. 2008"],
["13","Carson","72","72","4","No","No","No","Yes, est. 1979","No","No","Yes, est. 2004","No","No","No","No","No","No","Yes though HOME Funds","No","No","Yes though HOME Funds","No","No","No"],
["14","Cerritos","64","64","1","No","No","No","No","No","No","No","No","No","No","No","No","No","Yes, est. 2013","No","No","No","No","No","No"],
["15","Claremont","80","80","6","No","No","No","No","None exist, but Housing Element states that they could be built in Mixed Use district","No","Yes, est. 2005","Yes - vacancy rate 3%","No","Yes (Residential 30 Overlay, 30 units/acre), est. 2009","No","Yes, est. 2009","Yes, est. 2003","Yes, est. 2011 (updated)","No","No","No","No","No","No"],
["16","Commerce","55","55","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["17","Compton","57","57","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["18","Covina","3","3","1","No","No","No","No","No","No","Yes, est. 1993","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["19","Cudahy","28","28","2","No","No","No","No","Yes - 2013 Housing Element states that Municipal Code shall include SRO preservation","No","No","No","No","No","No","No","No","Yes, est. 2004","No","No","No","No","No","No"],
["20","Culver City","4","4","5","No","Mediation only (15.09)","Yes, est. 1981","No","No","No","Allows for Mixed-Use projects, est. 2005","Yes (5 or more units required, Site Plan and Tentative Map reviews), est. 2005","No","No","No","No","No","Yes","No","No","Yes","No","No","No"],
["21","Diamond Bar","14","14","4","No","No","No","No","No","No","Allows for Mixed-Use projects in some areas, est. 1998","Yes (relocation assistance program, assess the vacancy rate in multi-family housing within the City), est. 1999","No","No","No","No","No","Yes","No","No","Yes","No","No","No"],
["22","Downey","47","47","2","No","No","No","No","No","No","Yes, est. 2005","No","No","No","No","No","No","Yes though HOME Funds","No","No","No","No","No","No"],
["23","Duarte","58","58","3","No","No","No","No","No","No","No","No","No","No","No","Yes, est. 2005","Yes (19.30.040)","Yes though HOME Funds","No","No","No","No","No","No"],
["24","El Monte","32","32","2","No","No","No","Yes, est. 2015","No - none exist, but Housing Element states that they could be built in Santa Anita Overlay","No","Yes, est. 2014","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["25","El Segundo","79","79","1","No","No","No","No","Housing Element mentions that the Municiple Code should be amended to include provisions for SRO housing","No","Yes, est. 1997","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["26","Gardena","85","85","4","No","Mediation only (14.04)","Yes, est. 1987","Yes, est. 1987","Gardena Municipal Code was amended to permit SROs in the M-1 zone with a CUP","No","Yes, est. 2006","No","No","No","No","No","No","Yes, est. 2009","No","No","No","No","No","No"],
["27","Glendale","59","59","6","Yes, est. 2002","No","No","No","No","Yes (30.11), est. 2006","Yes, est. 2004","Yes, 180-day eviction notice, right of first purchase,reimbursement of moving expenses up to $500, est. 2009","No","No","No","San Fernando Road Corridor Redevelopment Project Area ONLY, est. 1992","Yes, est. 2004","No","No","No","No","No","No","No"],
["28","Glendora","22","22","1","No","No","No","No","No","No","Yes, est. 2003","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["29","Hacienda Heights","41","41","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["30","Hawaiian Gardens","23","23","2","No","No","No","No","No","No","No - but allows for MU projects, est. 2011","No","No","No","No","No","No","Yes, est. 2012","No","No","No","No","No","No"],
["31","Hawthorne","86","86","4","No","No","No","Yes, est. 1979","No","No","Yes, est. 2011","No","No","No","No","No","No","Yes though HOME Funds","No","No","Yes","No","No","No"],
["32","Hermosa Beach","84","84","3","No","No","No","No","No","Yes, est. 2013","No","Yes - first purchase units, including tenant purchase discounts, professional relocation assistance, Reimbursement for moving costs incurred, not to exceed $500.00, Extension of tenancy to complete school term, if necessary., est. 1980","No","Yes (17.42.130, Affordable Hosing Overlay Zone), est. 2012","No","No","No","No","No","No","No","No","No","No"],
["33","Hidden Hills","44","44","1","No","No","No","No","No","No","No","No","No","Yes - Affordable Housing Overlay (AHO), provides opportunities for lower-income affordable housing in Commercial-Restricted zone at a density of 20 units/acre, excluding density bonus., est. 2013","No","No","No","No","No","No","No","No","No","No"],
["34","Huntington Beach","17","17","6","No","No","No","No","Yes (230.46), est. 1991","No","Yes - Mixed Use Transit Zone, est. 2008","Yes - Conditional Use Permit required, impact study, parking and landscaping, relocation assistance(12 months), ant-discrimination, Prohibition of conversion of low and moderate housing funded through state or federal gov, est. 2004","No","No","No","Yes (230.26), est. 1992","Yes, est. 2004","Yes, est. 2010","No","No","No","No","No","No"],
["35","Industry","46","46","2","No","No","No","No","No","No","No","No","No","No","No","No","No","Yes though HOME Funds","No","No","Yes","No","No","No"],
["36","Inglewood","31","31","2","No","No","No","No","No","No","No","Yes - Special Use Permit, est. 1983","No","No","No","No","No","Yes","No","No","No","No","No","No"],
["37","Irwindale","53","53","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["38","La Cañada Flintridge","38","38","2","No","No","No","No","SROs are permitted with a Use Permit in the CPD zone","No","Yes, est. 2014","Yes - information report on the rental and vacancy rate of the property and provide an analysis of the effect of the proposed conversion of the property on the City’s low- and moderate-income housing supply, est. 2014","No","No","No","No","No","No","No","No","No","No","No","No"],
["39","La Habra Heights","39","39","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["40","La Mirada","81","81","2","No","No","No","No","Proposed for the future (Housing Element)","No","No","Needs to be processed under the Planned Unit Development Ordinance, est. 2008","No","No","No","No","No","Yes (http://www.cityoflamirada.org/Modules/ShowDocument.aspx?documentid=3353)","No","No","No","No","No","No"],
["41","La Puente","42","42","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["42","La Verne","69","69","5","No","No","No","Yes, est. 1984","No","No","Yes, est. 1997","Yes, est. 2013","No","No","No","No","Yes, est. 1994","No","Yes - mentioned in Housing Element, est. 2009","No","No","No","No","No"],
["43","Lakewood","56","56","4","No","No","No","Yes - Preservation of Mobile Home Parks, est. 2014","Allows SRO hotels with a Conditional Use Permit in M-2 zones","No","Yes, est. 2014","Yes - prohibits converting apartment to condominiums, est. 1979","No","No","No","No","No","Yes, est. 1978","No","No","No","No","No","No"],
["44","Lancaster","15","15","3","No","No","No","No","Permitted in some zones","No","Yes, est. 2010","No","No","No","No","No","No","Yes, est. 2008","No","No","No","Foreclosure Preservation Homeownership Program, est. 2007","No","No"],
["45","Lawndale","70","70","1","No","No","No","No","SRO housing allowed in the City’s commercial zones with a Special Use Permit","No","No","Yes - tenant relocation, monitoring of rental market, est. 1999","No","No","No","No","No","No","No","No","No","No","No","No"],
["46","Lomita","34","34","1","No","No","No","No","Conditionally permitted use in the RVD zone","No","No","No","No","No","No","No","No","Yes, est. 2009","No","No","No","No","No","No"],
["47","Long Beach","1","1","5","No","No","No","No","No","No","Allows for MU projects, est. 1988","Yes - Notification and relocation assisstance, a right of first refusal, exclusive right of 90 days to purchase or rent), est. 1991","No","No","No","Yes, est. 1991","Yes (In-Lieu Fee for Affordable Housing in Coastal Zone), est. 1980","No","No","No","Yes, est. 2011","No","No","No"],
["48","Los Angeles City","18","18","12","Yes, est. 1980","Yes (10-151.01-30), est. 1979","No","Yes (15-151.29), est. 1978","Yes, est. 2005","No","Yes, est. 1998","Yes (Relocation Assistance Program, 5% vacancy), est. 1980","No","No","Yes (12.22-D, 1-2), est. 2007","No","No","Yes (Handyworker Program), est. 2014 (revised)","No","Yes - only some specific Community Plans (Housing Element, Chapter 4), est. 1994","Yes","No","Yes, est. 2002","Yes, est. 2000"],
["49","Los Angeles County","89","89","4","No","No","No","Yes, est. 1988","No","No","Yes - Special Purpose Zone, est. 1983","No","No (Proposal for form-based code for future East Los Angeles 3rd Street Specific Plan)","No","No","No","No","Yes","No","No","Yes","No","No","No"],
["50","Lynwood","78","78","0","No","No","No","No","Permitted in specific zones, Ordinance 1659","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["51","Malibu","45","45","3","No","No","No","Yes (5.5.16), est. 1991","No","No","No","No","No","Yes (allows multi-family development by-right at a density of 20 units/acre), est. 2013","No","No","Yes (Ordinance No. 375), est. 2013","No","No","No","No","No","No","No"],
["52","Manhattan Beach","21","21","1","No","No","No","No","No","No","No","Yes - tenant notification, right to purchase, tenant purchase discounts, relocation expenses, and tenant discounts when condominiums are converted, est. 1991","No","No","No","No","No","No","No","No","No","No","No","No"],
["53","Maywood","87","87","2","No","No","No","No","No","No","Yes, est. 2009","No","No","No","No","No","No","Yes","No","No","No","No","No","No"],
["54","Monrovia","51","51","2","No","No","No","No","No","No","Yes, est. 2008","No","No","No","No","Yes, est. 1992","No","No","No","No","No","No","No","No"],
["55","Montebello","33","33","3","No","No","No","No","No","No","Yes, est. 2006","No","No","No","No","No","No","Yes","No","No","Yes","No","No","No"],
["56","Monterey Park","7","7","1","No","No","No","No","Permitted in specific zones","No","Yes, est. 2013","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["57","Norwalk","67","67","1","No","No","No","No","No","No","Allows for MU projects, est. 2012","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["58","Palmdale","20","20","2","No","No","No","Yes, est. 1985","No","No","Yes, est. 1994","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["59","Palos Verdes Estates","68","68","0","No","No","No","No","No","No","No","City parking requirements currently limit condominium conversion of some older units, thus acting as a deterrent to those seeking to convert this rental housing to more expensive condominium use","No","No","No","No","No","No","No","No","No","No","No","No"],
["60","Paramount","36","36","1","No","No","No","Yes, est. 1987","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["61","Pasadena","6","6","8","No","No","No","No","Allows for SROs in certain commercial zones. SROs exist in Pasadena.","No","Yes","Yes - Condominium Conversion Moratorium, est. 2007","No","No","No","Yes, est. 2001","Yes, est. 2001","Yes","Yes (4.17), est. 1988","No","Yes","No","No","No"],
["62","Pico Rivera","30","30","1","No","No","No","No","No","No","Yes, est. 2014","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["63","Pomona","9","9","2","No","No","No","Yes, est. 1992","No","No","No","No","No","No","No","No","No","Yes, est. 2013","No","No","No","No","No","No"],
["64","Rancho Palos Verdes","74","74","3","No","No","No","No","No","No","No","No","No","No","No","Yes, est. 1997","Yes, est. 1997","No","Yes, est. 2005","No","No","No","No","No"],
["65","Redondo Beach","43","43","1","No","No","No","No","No","No","Yes, est. 1996","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["66","Rolling Hills","13","13","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["67","Rolling Hills Estates","63","63","1","No","No","No","No","No","No","Yes, est. 1997","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["68","Rosemead","37","37","2","No","No","No","No","No","No","Yes, est. 2013","No","No","No","No","No","No","No","No","No","Yes","No","No","No"],
["69","San Dimas","27","27","1","No","No","No","No","No","No","Yes - Special Purpose Zone, est. 1990","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["70","San Fernando","16","16","3","No","No","No","No","No","No","Yes - Special Purpose Zone, est. 2008","No","No","No","No","Yes, est. 2009","No","Yes, est. 2000","No","No","No","No","No","No"],
["71","San Gabriel","11","11","3","No","No","No","No","No","No","Yes, est. 1995","Yes - comply with all current development standards of the zones, est. 2006","No","No","No","No","No","Yes - Handy Worker Minor Rehabilitation, est. 2009","No","No","No","No","No","No"],
["72","San Marino","12","12","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["73","Santa Clarita","50","50","3","No","No","No","Yes, est. 1990","No","No","Yes, est. 2013","No","No","No","No","No","No","Yes - http://www.santa-clarita.com/index.aspx?page=518, est. 2013","No","No","No","No","No","No"],
["74","Santa Fe Springs","2","2","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["75","Santa Monica","76","76","7","Yes, est. 1979","Yes (Article XVIII), est. 1979","No","Yes, est. 1979","No","No","Allows for MU projects, est. 1995","Yes (9.04.16.02.010, approval of rent control board, rehab), est. 1988","No","No","No","Yes, est. 1983","Yes, est. 2014","Mentioned in Housing Element for future","No","No","No","No","No","No"],
["76","Sierra Madre","29","29","2","No","No","No","No","No","No","Yes, est. 2014","Yes (16.36) - tenant noticing, relocation compensation, right of first purchase, conditional use permit, est. 1999","No","No","No","No","No","No","No","No","No","No","No","No"],
["77","Signal Hill","8","8","1","No","No","No","No","No","No","Allows for MU projects, est. 1993","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["78","South El Monte","77","77","2","No","No","No","No","No","No","Allows for MU projects, est. 2012","No","No","Yes, est. 2012","No","No","No","No","No","No","No","No","No","No"],
["79","South Gate","75","75","1","No","No","No","No","No","No","Yes - Special Purpose Zone, est. 2014","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["80","South Pasadena","83","83","3","No","No","No","No","No","No","Allows for MU projects","No","No","No","Yes","No","No","Yes (Home Improvement Program), est. 2001","No","No","No","No","No","No"],
["81","Temple City","10","10","2","No","No","No","No","No","No","Allows for MU projects, est. 2005","Yes, est. 1979","No","No","No","No","No","No","No","No","No","No","No","No"],
["82","Torrance","52","52","2","No","No","No","No","Has SROs and allows for more","No","Allows for MU projects, est. 2005","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["83","Vernon","26","26","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["84","Walnut","60","60","3","No","No","No","No","Allows for SROs under M-1 zoning","No","Yes (Only allowed in Commercial Zoning under Special Plan process), est. 2013","No","No","Yes - The Francesca Mixed-Use, Snow Creek Village, and Walnut Grove Specific Plans, est. 2013","No","No","No","Yes - effective September 23, 2014, http://www.ci.walnut.ca.us/general.asp?id=124, est. 2014","No","No","No","No","No","No"],
["85","West Covina","24","24","3","No","No","No","Yes (15.184), est. 1984","No","No","Allows for MU projects, est. 2012","No","No","No","Yes, est. 2013","No","No","No","No","No","No","No","No","No"],
["86","West Hollywood","25","25","7","Yes, est. 1985","Yes, est. 1985","No","No","No","No","Yes, est. 2012","Yes (purchasing rights for the tenants, compliance w/ zoning), est. 2001","No","No","No","Yes (19.22), est. 1986","Yes - projects with 10 or fewer units may choose to pay a fee, or provide an affordable rental unit., est. 2001","Mentioned in Housing Element for future","No","Yes, est. 2001","No","No","No","No"],
["87","Westlake Village","5","5","1","No","No","No","No","No","No","Yes, est. 1985","No","No","No","No","No","No","No","No","No","No","No","No","No"],
["88","Whittier","65","65","0","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No","No"]]

// Original inventoryText:

/* var inventoryText = [["0","Alameda","78","600562","Alameda","No","No","Yes, Rent Review Advisory Committee. Mediation only (Early 1990s)","No","No","Limits conversions if the percentage of rental units drops below 40% of the total available housing stoc. Must meet requirements of Design Review and the Planning Board. Tenant relocation assistance plan is required, which must give particular attention to the needs of elderly, handicapped, households with minor children, and households of low and moderate income. Ratio of owner-occupied units must not exceed 60% of the total number of dwelling units available. Year: 1983","Yes (2013)","Yes (1989)","Office $3.00/sf, Retail $1.50/sf, Hotel/motel $770/room (1989, revised 2001) ","Yes","For all Residential Developments of five (5) or more units, at least fifteen percent (15%) of the total units must be Inclusionary Units restricted for occupancy by Very Low-, Low- or Moderate-Income Households. Breakdown: 4% affordable to very low, 4% affordable to low, 7% affordable to moderate-income households. Yes in-lieu fee. (2004) Yes in-lieu fee for 9 or fewer units.","Yes (2009)","No","No","https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?nodeId=CHIIAD_ARTIIBOCO_2-23REREADCO_2-24--2-29RE","https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?nodeId=CHXXVIIDEFE_27-3DEIMFE_27-3.12FEFEES","https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?nodeId=CHXXXDERE_ARTIZODIRE_30-17DEBOOR","https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?nodeId=CHXXXDERE_ARTIZODIRE_30-16INHOREREPR","https://www.acgov.org/auditor/sleb/sourceprogram.htm","https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?nodeId=CHIIIFITA_ARTIVSPTAFI_DIVVPRLE_3-70.70ORTARAAPEXGOPRENSPTAUSTAPRTACOPEET_3-70.90ACFOLICUREREDIPUFOAC","Condominium Conversion:  https://www.municode.com/library/ca/alameda/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22condominium%20conversion%5C%22%20vacant%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=CHXXXDERE_ARTIZODIRE_30-8COMUHO_30-8.5PR","Housing trust fund: http://alamedaca.gov/sites/default/files/department-files/2014-08-18/23._fund_combined_0.pdf"],

["1","Albany","79","600674","Alameda","No","No","No","No","Yes","Yes - not to exceed 3% of multi-family rental housing and will not displace significant percentage of low and moderate income, senior or disabled tenants. (2002)","No","No","No","No","15% of units to be made affordable to low income households; Yes in-lieu fee. (2005)","No","Yes (1987)","No","code: http://www.cityofalbany.net/city-council/municipal-code","housing element: http://www.albanyca.org/index.aspx?page=779","","","","","",""],

["2","American Canyon","89","601640","Napa","No","No","No","No","No","Yes - restricts when rentals become less than 40% of housing stock (2006)","Yes","No","No","No","10% affordable to low income households.  Yes in-lieu fee. (2001, amended 2006)","Yes - increased bonus (2014)","No","No","code: http://qcode.us/codes/americancanyon/","density bonus: 19.27.030","","","","","",""],

["3","Antioch","92","602252","Contra Costa","No","No","No","No","Yes","vacancy rate must be above 4.5% improvements required (2006) ","Yes (2008)","No","No","No","No","No","No","No","code: http://library.amlegal.com/nxt/gateway.dll/California/antioch/cityofantiochcaliforniacodeofordinances?f=templates$fn=default.htm$3.0$vid=amlegal:antioch_ca","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/antioch_%205th_draft122214.pdf","condominium conversion: art. 31, Ord. 1070-C-S","","","","",""],

["4","Atherton","25","603092","San Mateo","No","No","No","No","No","No","No","No","No","No","No","No","No","No","code: http://www.codepublishing.com/ca/atherton.html","housing element: http://www.ci.atherton.ca.us/DocumentCenter/View/1501","","","","","",""],

["5","Belmont","51","605108","San Mateo","No","No","No","No","No","Yes. Year: 1974","No","No","No","No","No","No","No","No","","","","","","","",""],

["6","Belvedere","34","605164","Marin","No","No","No","No","No","No","No","No","No","No","No","No","No","Yes","code: http://www.cityofbelvedere.org/index.aspx?NID=92","","","","","","",""],

["7","Benicia","3","605290","Solano","No","No","No","Yes (1987)","No","Vacancy rate in City must be above 5%; improvements required; tenants' granted discounts; no rent increase in 2 years; moving expenses; relocation assistance. Year: 1987","No","No","No","No","10% affordable residential units (2011). Yes in-lieu fee. ","No","No","No","code: http://www.codepublishing.com/ca/benicia/","","","","","","",""],

["8","Berkeley","80","606000","Alameda","Yes (1980, amended 1982, 1990, 2000, 2004)","Complex formula with 29 factors annually calculated; 3.5% with $30/unit cap (1980, last amended 2005)","Yes (1980) funded by fees on all registered rental units. Independantly elected board, not under the authority of the City Council, with separate staff.","Yes","Yes - BHA provides subsidy for 98 units of SRO","100 units/yr. However, to the extent the number of units approved for conversion in any given year is less than 100, the quota for the following year may be increased by an equivalent amount, which may be carried forward from year to year, but shall not exceed a total of 200 rental units in any given year (2009)","Yes","Yes - Affordable housing mitigation fee (2011)","Office $5.00/sf, Retail $5.00/sf, Industrial $2.50/sf when greater than 7,500 sf. 20% of fees go towards child care operating subsidies (1988)","Yes","For-sale: no minimum percentage, but general requirement is 20%. Rental: 50% of units to be affordable to low income households (1999). Yes on in-lieu fee.  ","No","No","Yes (1988)","code: http://codepublishing.com/ca/berkeley/","condominium conversion: 21.28.040","SRO: http://www.ci.berkeley.ca.us/BHA/Home/Housing_for_Homeless_Disabled_Individuals.aspx","Rent stablization and just cause: Ch. 13.76","housing impact fee: 22.20.065","inclusionary housing: 23C.12.030","",""],

["9","Brentwood","64","608142","Contra Costa","No","No","No","No","No","Vacancy rate will be considered during application review, improvements required (2008)","No","No","No","No","Yes - 2% affordable units for more than 25 lots. Yes in-lieu fee (2005, amended 2007 and 2012) Ownership units shall remain affordable for 45 years, rental 55 years (2015)","No","No","No","code: http://qcode.us/codes/brentwood/","inclusionary housing: 17.725","condominuim conversion: 17.740","","","","",""],

["10","Brisbane","26","608310","San Mateo","No","No","No","No","Yes","Vacancy rate in City must be above 5% to allow conversions. Year: 1984","Yes","No","No","No","15% affordable to low-income households; Yes in-lieu fee. (2009)","No","No","No","Code: https://www.municode.com/library/ca/brisbane/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22condominium%20conversion%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT17ZO_CH17.30CO_17.30.060FI","Condominium conversion: 17.30","density bonus: 17.31","SRO: http://www.ci.brisbane.ca.us/sites/default/files/ChapterIV-draft.pdf","","","",""],

["11","Burlingame","52","609066","San Mateo","No","No","No","No","No","Conversion allowed only when conversion produces 20 or more condominium units. Year: 1981, amended 2003","Yes","No","No","No","10% affordable to low-income households.  Yes in-lieu fee. (2003)","No","No","No","http://qcode.us/codes/burlingame/","Condomium conversion: 26.32","","","","","",""],

["12","Calistoga","90","609892","Napa","No","No","No","6% of base rent or 100% of % change in CPI (1984, amended 2007)","No","No","Yes","Housing linkage fee - All new construction or additions to gross floor area greater than 10% ","Retail $0.80; Office $1.00; Tourist Accommodations $1.40; Industrial $0.50 (2008)","No","20% affordable to low- and moderate- income households (1995). 10% affordable to low- and moderate- income households (1989). Yes in-lieu fee.","No","No","No","code: http://codepublishing.com/ca/calistoga/mobile/?pg=Calistoga17/Calistoga1708.html#17.08.020","inclusionary housing: 17.08.020","housing linkage fee: 17.08.040","mobile home: 2.22.070","","","",""],

["13","Campbell","13","610345","Santa Clara","No","No","Yes- Rental Dispute Program-mediation only (1997, amended 1998)","No","Yes - refine code definition to conditionally allow SRO within the R-3-S zone","No","Yes","No","No","No","For projects of 10 or more units, 6% affordable to very low- and 9% affordable to low/moderate-income households (2006)","Yes (2004, amended 2008)","Yes (South County Housing)","No","code: https://www.municode.com/library/ca/campbell/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT21ZO_ART3DEOPST_CH21.20DEBOOTINAFREUNSEHOCHFA_21.20.080DEBOCOCO","housing element: http://www.ci.campbell.ca.us/DocumentCenter/View/2523","density bonus: 21.20.010","Rent review: 6.09","inclusionary housing: 21.24","","",""],

["14","Clayton","60","613882","Contra Costa","No","No","No","No","Yes - identify zoning to encourage and facilitate supportive housing and single-room occupancy units (Assembly Bill 2634)","No","No","No","No","No","5% affordable to very low- and 5% affordable to low-income households. Yes in-lieu fee. (2010)","No","No","No","code: ","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/clayton_5th_draft060914.pdf","SRO: housing element","","","","",""],

["15","Cloverdale","1","614190","Sonoma","No","No","No","Yes (1986)","No","No","No","No","No","Yes - Affordable housing fund per 18.13.080","For-sale: 15% affordable to very low, low, and moderate-income households. Rental: 15% affordable to very low and low-income households. Yes in-lieu fee. (2012)","No","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","code: http://www.codepublishing.com/ca/Cloverdale/html/cloverdale18/Cloverdale1813.html","inclusionary housing: 18.13.050","density bonus: 18.13.060","housing element: http://www.cloverdale.net/DocumentCenter/View/1613","","","",""],

["16","Colma","27","614736","San Mateo","No","No","No","No","No","No","No","No","No","No","20% affordable to very low, low, and moderate-income households. Yes in-lieu fee. (2005)","No","No","No","code: http://www.colma.ca.gov/index.php/municipal-code-124","housing element: http://www.colma.ca.gov/index.php/town-departments/planning/general-plan-update/1125-2015-housing-element/file","inclusionary housing : program 3.2","","","","",""],

["17","Concord","93","616000","Contra Costa","No","No","No","80% of % increase in CPI (2002)","Yes -Continue to allow SRO in accordance with State law. ","Max base number is equal to five percent of the total rental units existing in developments of four or more units at the beginning of the fiscal year as determined and certified by the Housing Division (2008).  However, applications for Condo conversions have not been submitted in recent years and currently, the City has no formal applications for a condo conversion.","Yes (2007)","No","No","No","For-sale: either 6% affordable to low-income households or 10% affordable to moderate-income  households. Rental: either 6% affordable to very low-income households or 10% affordable to low-income households for units receiving City assistance. Yes in-lieu fee. (2004)","No","No","No","code: http://www.codepublishing.com/ca/concord/","housing element: http://www.cityofconcord.org/pdf/projects/housingElement/11072014.pdf","condominuim conversion: Section 17.50.150","affordable housing: 18.185.040","SRO: Program H-1.5.6","","",""],

["18","Corte Madera","20","616462","Marin","No","No","No","No","Yes - Add “single room occupancy housing” to the definitions section of the Zoning Ordinance as an allowed use in multifamily zoning districts.","Vacancy rate in City must be above 5% (2009, amended 2010) yes in-lieu fee","No","Yes (2001)","Depending on non-residential use, $0.40 - $8.38 per sq. ft.  Uses shall include, but are not limited to, assistance to nonprofit providers of housing, equity participation loans, acquisition of land for affordable housing, and public/private partnership arrangements (2001)","No","5% affordable to very low-, 10% affodrable to low-, and 10% affordable to moderate- income households. Yes in-lieu fee. (2003)","Yes (2003)","No","No","code: https://www.municode.com/library/ca/corte_madera/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT18ZO_CH18.08RREDI_IGEPR_18.08.030SPRECEPEUSCOUSREDI","housing element: http://townofcortemadera.org/DocumentCenter/View/1694","sro: policy H-1.4a","","","","",""],

["19","Cotati","2","616560","Sonoma","No","No","No","100% of % increase in CPI or 6% cap","No","Relocation Assistance Program, vacancy rate considered (2015)","No","Yes","Fee shall be increased or decreased annually by the percentage change in the Construction Cost Index for the prior year (2006)","No","20% affordable to very low, low, and moderate income households. Yes in-lieu fee. (2004)","No","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","code: http://www.codepublishing.com/CA/Cotati/","housing element: http://www.cotati.generalplan.org/sites/default/files/Cotati_Public%20Draft%20Housing%20Element_4-16-15.pdf","mobile home: 19.14.004","condominium conversion: 17.74.030","","","",""],

["20","Cupertino","14","617610","Santa Clara","No","No","No","No","Yes","Vacancy rate in City must be above 5%. Relocation plan; replacement housing must be available in the housing market area for 25% or less of household income; improvements required. Year: 1992, amended 2011.","Yes","Yes","Office/industrial, hotel, and retail: $5.23/sf. Planned Industrial Zone: $2.62/sf. (1992)","Yes","Rental: 15% affordable to very low- and low-income households. For-sale: 15% affordable to median and moderate-income households (1992, 2002); BMR (2014)","Yes (1991, amended 2014)","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","code: http://library.amlegal.com/nxt/gateway.dll/California/cupertino/title19zoning/chapter19172belowmarketratehousingprogra?f=templates$fn=altmain-nf.htm$q=%5Band%3A%E2%80%9Cbelow%20market%20rate%E2%80%9D%5D%20$x=server$3.0#LPHit1","Density bonus: 19.56.030","BMR: 19.172","housing trust fund: P.3-12 https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwirqIud7aTJAhXIWSYKHURYDUQQFggeMAA&url=http%3A%2F%2Fwww.cupertino.org%2FHE%2F&usg=AFQjCNERyz5dVIOAkHqV8rRWTJEh9S4lUA&sig2=_aX67sOLNCPDU-ZBTL0Uwg","SRO: Housing Element P. 3-15 (Program 14)","","",""],

["21","Daly City","53","617918","San Mateo","No","No","No","Mobile home Rent Review Commission (1980)","Yes","Requires structural or mechanical changes reasonably necessary to adequately protect the public health, safety and welfare. Relocation assistance program. Year: 1980, amended 1981","Yes (in partnership with Project Sentinel and EPACANDO)","Yes (2014)","No","Yes (2014)","6% affordable to very low-income households; 15% affordable to low and moderate income households (1993)","No","No","No","https://www.municode.com/library/ca/daly_city/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22Condominium%20Conversion%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT17ZO_CH17.37COCOCO","Condomium conversion: Chapter 17.37","mobile home: 2.52","housing impact fee: 17.47","","Housing trust fund: 17.47.150","Foreclosure assistance: http://www.dalycity.org/Asset2954.aspx",""],

["22","Danville","94","617988","Contra Costa","No","No","No","No","Yes","No","Yes","No","No","No","5% affordable to very low-; 10% affordable to low-; and 10% affordable to moderate- income households. Yes in-lieu fee. (1994)","No","No","No","code: http://library.amlegal.com/nxt/gateway.dll/California/danville_ca/danvillecaliforniamunicipalcode?f=templates$fn=default.htm$3.0$vid=amlegal:danville_ca","housing element: http://www.danville.ca.gov/Services/Planning-Services/General-Plan/Housing-Element-2014-2022/","","","","","",""],

["23","Dixon","4","619402","Solano","No","No","No","No","Yes - permitted in DOWNTOWN COMMERCIAL DISTRICT","No","No","No","No","No","No","No","No","No","code: http://www.codepublishing.com/ca/dixon/","SRO: 18.09","","","","","",""],

["24","Dublin","81","620018","Alameda","No","No","No","No","Yes - conditionally permitted in the C-2 (General Commercial) zone.","7% annual max (2005)","Yes (2005)","No","Yes (2005)","No","For projects of 20 units or more, 12.5% of the units must be BMR units. For-sale: 60% affordable to moderate-income households and 40% to low-income households.  Rental: 50% affordable to moderate-income households; 20% to low-income households; and 30% to very low- income households (2002, Revised 2003, 2005, 2008)","No","No","No","code: http://www.codepublishing.com/ca/dublin.html","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/dublin_5th_draft062014.pdf","SRO: program 24","Condominium conversion: 8.54.030","commercial linkage: 7.86.020","inclusionary zoning: 8.68.030","",""],

["25","East Palo Alto","28","620956","San Mateo","Yes (2010)","One increase per year, shall not exceed 10%; 80% of increase in the CPI (1983, last amended 2010).","Yes","Yes (1983)","Yes: allowing SRO housing in the R1 (2011)","Vacancy rate in City must be above 4.15% (2012)","Yes","Yes (2013)","No","No","5%  affordable to very low and 10% affordable to low-income households. Yes in-lieu fee. (1994, last amended in 2004)","Yes (2008)","Yes (Ravenswood, NCLT)","Yes (2006)","code: https://www.municode.com/library/ca/east_palo_alto/codes/code_of_ordinances?nodeId=EAST_PALO_ALTO_CALIFORNIA","housing element: http://www.ci.east-palo-alto.ca.us/documentcenter/view/437","SRO: H 5.8","","","","",""],

["26","El Cerrito","61","621796","Contra Costa","No","No","No","No","No","Annual limitation shall be determined by balancing the existing vacancy rate, the number of units produced in the previous year and the existing housing stock (2008)","No","No","No","No","No","Yes (2008)","No","No","code: https://www.municode.com/library/ca/el_cerrito/codes/code_of_ordinances?nodeId=TIT19ZO_PTVIGETE_CH19.47TEDE_19.47.020DE","","","","","","",""],

["27","Emeryville","82","622594","Alameda","No","No","No","No","No","Require buiding improvements, landscaping upgrades, and public improvements (2013)","Yes (2007)","Yes (2014)","Yes (2014)","No","Set-Aside Ordinance- For-sale: 20% affordable to moderate; Rental: 9% affordable to moderate, 6% affordable to very low-income households for at least 25 years (1990, revised 2008). Replaced by Affordable Housing Program- For-sale: 20% affordable to moderate; Rental: affordable housing impact fee or 6.9 percent of units as affordable units for low-income households for at least 55 years (2014).  No In-Lieu","Yes (2013)","No","No","code: http://www.codepublishing.com/ca/emeryville/","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/emeryville_5th_draft072114.pdf","impact fee/linkage fee: Sec. 3 (part), Ord. 14-009","","","","",""],

["28","Fairfax","45","623168","Marin","No","No","No","No","No","Yes. Year: 1981","Yes","No","No","No","No","No","No","No","","","","","","","",""],

["29","Fairfield","67","623182","Solano","No","No","No","annual adjustment must not exceed 6% (1998)","Yes - Housing element 6.2C","Yes (2012) - vacancy rate must be above 6%, or 3% if the project is consistent with the city's intent; tenant assistance","Yes (2007)","No","No","Yes","No","No","No","No","code: http://www.codepublishing.com/CA/Fairfield/#!/Fairfield25/Fairfield2505.html","","","","","","",""],

["30","Foster City","29","625338","San Mateo","For redevelopment/conversion of a site","No","No","No","No","Requirement for deed restrictions on resale (unless financing is impossible), or 1% of gross sales must be contributed to the City, and comparable rental housing must be available in the Housing Market Area. Requires relocation displacement or mitigation plan. Includes tenant protection provisions. 10% of units must be set aside for low and moderate income. Year: 1981","No","No","No","No","20% affordable to very low, low, and moderate income households (2010)","No","No","No","http://www.codepublishing.com/ca/fostercity/","Condomium conversion: chapter 17.76","","","","","",""],

["31","Fremont","86","626000","Alameda","No","No","Yes-Residential Rent Increase Dispute Resolution Ordinance- mediation only (1997)","3% or $10/month or 60% of % change in CPI (1995)","No","100 units/year and roll-overs of any unused units from an immediate prior year if the apartment vacancy rate at the time is greater than 5%, or borrowing up to 20 units in allocations from future years (1990, Amended 2006); improvements required; homeowners' association; relocation assistance and subsidy (2009).","No","Yes","No","No","For-sale: 15% of all living units should be affordable. Rental: affordable housing impact fee required, exempt for units that are subject to rent regulatory agreement with term of 55 years and which are required to be rented at affordable rents to very low or low income households. Yes on in-lieu fee (2009) the city must have adequate sites zoned to accommodate 5,455 housing units for the period from 2015 to 2023, including sites for 857 extremely low income units, 857 very low income units, 926 low income units, and 978 moderate income units. (2015)","No","No","Yes","code: http://www.codepublishing.com/ca/fremont/","condominium conversion: 18.190.060","mobile home: 9.55.050","","","","",""],

["32","Gilroy","11","629504","Santa Clara","No","No","No","Lesser of 5% or 80% of CPI (1987)","Np","Vacancy rate in City must be above 5% (2012)","Yes","No","No","No","15% affordable to very low, low, and moderate income household (2006)","Yes (1995, amended 2014)","Yes (South County Housing/Una Nueva Esperanza)","No","code: http://www.codepublishing.com/ca/gilroy/","","","","","","",""],

["33","Half Moon Bay","30","631708","San Mateo","No","No","No","No","No","Conversions allowed determined by factors such as vacancy rate and recent growth or decline in the number of multi-family dwellings  (1994)","Yes","No","No","No","6% affordable to very low-income households; 7% affordable to low-income households; 7% affordable to moderate-income households. Yes in-lieu fee. (1996, last ameded 2010)","No","No","No","code: http://www.codepublishing.com/CA/HalfMoonBay/#!/HalfMoonBay17/HalfMoonBay1702.html","condominium conversion: 17.62","BMR: 18.35","Density bonus: 18.42","","","",""],

["34","Hayward","48","633000","Alameda","Yes (2003)","5% max annual increase (1983, amended 2003).","Rent Review Officer- may settle by arbitration ","5 lesser of 3% or 60% CPI to 8% (1980)","No","Yes (2007)","Yes","No","No","No","For-sale: 15% of units affordable to moderate-income households. Rental: 15% of units affordable to very low- and low-income households. Yes in-lieu fee. (2012) ","Yes (2005)","No","Yes","","","","","","","",""],

["35","Healdsburg","76","633056","Sonoma","No","No","No","No","No","No","No","No","No","No","For projects of 7 units or more, 15% affordable to very low-, low-, and moderate-income households. Yes in-lieu fee. (2005)","No","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","code: http://www.codepublishing.com/CA/Healdsburg/#!/Healdsburg17/Healdsburg1704.html#17.04.730 ","condo conversion: 17.04","","","","","",""],

["36","Hercules","62","633308","Contra Costa","No","No","No","No","Yes -  permitted conditionally in the Historic Town Center zone","No","Yes","No","No","No","15% affordable units and of these, 40% must be affordable to very low-income households. Yes in-lieu fee. (2006)","No","No","No","code: http://www.codepublishing.com/CA/Hercules/#!/Hercules10/Hercules1019.html","condo conversion: 10-19.104","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/hercules_5th_draft012215.pdf","","","","",""],

["37","Hillsborough","31","633798","San Mateo","No","No","No","No","No","No","No","No","No","No","No","No","No","No","code: https://www.municode.com/library/ca/hillsborough/code_of_ordinances","","","","","","",""],

["38","Lafayette","75","639122","Contra Costa","No","No","No","No","No","Max 12 units in one calendar year; max 20 units in total. Other requirements: sound control; laundry facilities; private storage space; parking; landscape maintenance; refurbishing and restoration. Flexible vacancy rate. Year: 1979, amended 1985.","No","No","No","No","No","No","No","No","https://www.municode.com/library/ca/lafayette/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22condominium%20conversion%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT6PLLAUS_PT6SU_CH6-32COCO","Condominium Conversion: Chapter 6-32; Density Bonus: Chapter 6-36","","","","","",""],

["39","Larkspur","46","640438","Marin","No","No","No","No","No","Vacancy rate in City must be above 5%. 15% inclusionary unit requirement. Rent increases no more than 50% of the consumer price index. Year: 1981, amended 2004)","No","No","Yes (2011)","No","For projects of 5-14 units, For-sale: 15% affordable to low- and moderate-income households. Rental: 15% affordable to very low- and low-income households.  For developments of 15 or more units: at least 20% of  units shall be affordable as outlined above. Yes in-lieu fee. (2005)","No","No","No","http://www.codepublishing.com/ca/larkspur.html","Zoning: 18.25","density bonus: 18.26","","","","",""],

["40","Livermore","49","641992","Alameda","No","No","No","No","No","Max 3% of the City’s stock of rental units, not to exceed a total of 150 units a year. Vacancy rates are also considered (1999, amended 2000)","Yes (2005)","Yes (1999)","Yes (1999, last amended 2015)","No","7.5% affordable to low-income households and 7.5%  affordable to moderate-income households (2005) Affordable Homeownership Opportunities","No","No","No","code: http://www.codepublishing.com/ca/livermore.html","commercial linkage: 3.26.060","BMR: http://www.cityoflivermore.net/citygov/cd/hhs/housing/opps.asp","","","","",""],

["41","Los Altos","42","643280","Santa Clara","No","No","No","No","Yes - allow SROs as a conditional use in the CT district","Vacancy rates will be considered (2010)","No","No","No","No","For-sale: 10% of units shall be affordable to moderate income households. Rental: 15% of units shall be affordable to low or 10% to very low income households. For projects with 5-9 units, if the developer can demonstrate that affordable housing units in a project will be financially infeasible, requirement for affordable housing may be waived (1995, amended 2009)","No","Yes (South County Housing)","No","code: https://www.municode.com/library/ca/los_altos/codes/code_of_ordinances?nodeId=SUHITA","housing element: http://www.losaltosca.gov/sites/default/files/fileattachments/Community%20Development/page/4616/2015-2023_los_altos_housing_element_final.pdf","SRO: Supp. No. 27 Ord. 2015-409","","","","",""],

["42","Los Altos Hills","15","643294","Santa Clara","No","No","No","No","No","No","No","No","No","No","No","No","Yes (South County Housing)","No","code: http://www.losaltoshills.ca.gov/city-government/municipal-code/code","","","","","","",""],

["43","Los Gatos","10","644112","Santa Clara","No","5% max annual increase or 70% of the increase in the CPI, whichever is greater. No more than once a year. (1980, amended 2004).","Town's Rental Dispute Mediation and Arbitration Ordinance (2004)","100% CPI or 5% (1980)","Yes - Single room occupancy units are permitted as multi-family units","Yes - part of the Below Market Price Guidelines (2009)","No","No","No","No","For projects of 5-19 units, 10% of units should be BMR. For projects of 20-100 units, percentage of BMR units is determined by the following formula: Number of BMP units equals .225 (total # of market rate units) minus 2.5. For projects above 100 units, 20% of units should be BMR. Yes in-lieu fee. (1979) (2009); AFFORDABLE HOUSING OVERLAY ZONE (2013)","Yes (2012)","Yes (South County Housing)","No","code: https://www.municode.com/library/ca/los_gatos/codes/code_of_ordinances","housing element: http://www.losgatosca.gov/DocumentCenter/View/13555","","inclusionary housing: 29.82.515","","","",""],

["44","Martinez","95","646114","Contra Costa","No","No","No","No","No","Vacancy rate in City must be above 5%. Relocation expenses must be 1.5x the monthly rental rate. Other requirements: 150 cubic/unit private storage space; 100 sq. ft appurenant usable private area; 100 sq. ft open space; energy conservation; must be approved by Design Review. Downtown Martinez Core Area exempted from some regulations. Year: 1979","No","No","No","No","No","No","No","No","https://www.municode.com/library/ca/martinez/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22condominium%20converseion%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=CD_ORD_TIT21SU_CH21.56RECOREUNCO_21.56.001PU","Condominium Conversion: article 21.56; Density Bonus: Chapter 22.57","","","","","",""],

["45","Menlo Park","36","646870","San Mateo","No","No","No","No","No","Yes. Year: 1974","No","No","Commercial development $6.00/sf, Research and development $10.00/sf. 10,000 sf exemption. Fees go toward 'Below Market Rate Reserve'. (1989, revised in 2001)","Yes","For projects of 5-20 units, min. 10% of units shall be BMR to very low-, low-, and moderate-income households. For projects above 20 units, at least 15% of units shall be BMR to very low-, low-, and moderate-income households. Yes in-lieu fee. (2001)","No","No","No","http://www.codepublishing.com/dtSearch/dtisapi6.dll?cmd=getdoc&DocId=175&Index=D%3a%5cProgram%20Files%5cdtSearch%5cUserData%5cCA%5cMenloPark_index&HitCount=30&hits=7+30+5a+69+6f+7b+7c+82+96+9a+9c+9d+a3+c9+dc+101+111+145+1a3+2c1+2db+2dc+3e3+3e4+3f6+42b+479+4da+4db+4fe+&SearchForm=%2fCA%2fMenloPark%2fMenloPark_form%2ehtml","Inclusionary housing: 16.96.020","Housing trust fund: http://www.housingtrustsv.org/wp-content/uploads/2014/05/Housing_Trust_SV-NL-Feb-2105-web.pdf","","","","",""],

["46","Mill Valley","23","647710","Marin","No","No","No","No","No","Vacancy rate in City must be above 5%. Other requirements: Space and connections for the installation and operation for laundry equipment; one cubic foot of storage area for each three feet of gross floor area. Annual rent increases for tenants awarded lifetime leases may not exceed a rate equal to one-half the annual Bay Area inflation rate. Relocation assistance in the amount of three month’s rent based on HUD’s annual Fair Market Rent for apartment size for Marin County; leasehold rights. Year: 1977","Yes","No","No","No","For projects of 10 or more units with a gross density of less than seven units per acre, 10% affordable by moderate income households. For projects of 10 or more units with a gross density of seven or more units per acre, 15%  affordable by moderate income households. Yes in-lieu fee for 2-9 unit projects. (1988)","No","No","No","Condominium conversion: http://www.qcode.us/codes/millvalley/view.php?topic=20&frames=on","","","","","","",""],

["47","Millbrae","32","647486","San Mateo","No","No","No","No","No","Yes, including a relocation assistance program for tenants. Year: 1976","No","No","No","No","15% of units to be BMR (2014)","No","No","No","Condominium conversion: http://www.codepublishing.com/CA/Millbrae/#!/Millbrae10/Millbrae1025.html","","","","","","",""],

["48","Milpitas","100","647766","Santa Clara","No","No","No","50% of CPI or 8% cap (1992)","No","Vacancy rate in City must be above 5% (2008)","No","No","No","No","Affordable Housing Requirement as part of Zoning Ordinance requires 20% of new units to be affordable. Allows project-by-project negotiation. (2008)","No","Yes (South County Housing)","No","code: https://www.municode.com/library/ca/milpitas/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9Cmobile%20home%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TITIIIBUPR_CH30MOHOPAREIN","mobile home: III-30-12.00","","","","","",""],

["49","Monte Sereno","16","648956","Santa Clara","No","No","No","No","Yes - permitted in Rm zone and first Baptist Church per Program H-2.5","No","No","No","No","No","No","No","Yes (South County Housing)","No","code:","housing element: http://www.montesereno.org/DocumentCenter/Home/View/674","","","","","",""],

["50","Moraga","63","649187","Contra Costa","No","No","No","No","No","Limited to the town's potentially convertible rental stock; no tenant rent increases for 2 years; Vacancy rates of existing apartment residential units not a criterion. Year: 1981.","No","No","No","No","No","No","No","No","","","","","","","",""],

["51","Morgan Hill","44","649278","Santa Clara","No","No","No","Twice the CPI or 15% (1988, amended 1990)","No","Average vacancy rate in City must be above 5%. Other requirements: sound transmission; utility metering; private storage space; laundry facilities; landscape maintenance; refurbishing required. Nontransferable right of first refusal; rent shall not be increased for two years;  a lifetime lease with reasonable annual rent increases for senior citizens; a three-year lease with reasonable annual rent increases for low and moderate income households; moving expenses of two times the monthly rent. Year: 1983","No","No","No","No","No","No","Yes (South County Housing)","No","Municipal Code: https://www.municode.com/library/ca/morgan_hill/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22Condominium%20Conversion%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT17SU_CH17.36COCO","Condominium conversion: 17.36 ","","","","","",""],

["52","Mountain View","41","649670","Santa Clara","No","No","Funds a mediation program","No","No","Prohibits conversion if the number of rental units falls below floor of 15,373. Temporary housing required for tenants displaced due to conversion. Additional tenant relocation assistance added in 2009. Year: 1979, amended 2009.","No","Yes (2013)","The amount of the fee shall be computed as follows: (Gross Square Feet Nonresidential Floor Area Minus Existing Floor Area) times (Applicable Fee as listed in Table 36.40-1) equals Housing Impact Payment (2013)","No","10% of units to be BMR. Yes in-lieu fee. (2013)","No","Yes (South County Housing, Anchorage Community Land Trust)","No","Municipal code: https://www.municode.com/library/ca/mountain_view/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22condominium%20conversion%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=PTIITHCO_CH28SU_ARTVIIRECOCO","Condomium conversion: Art VII SEC 28.70-76","BMR: div 2 sec. 36.40.10","","","","",""],

["53","Napa","87","650258","Napa","No","No","No","8% cap (1983)","Yes (2003)","Vacancy rate must be above 5% and cannot exceed the number of multifamily units permits issued the year prior or the difference between the vacancy rate and 5%. Year: 1987","No","Yes (2012)","Yes (2012)","No","10% of units to be affordable to very  low- and low- income households. Yes in-lieu fee. (1999, last amended 2003)","Yes - supplemental density bonus up to maximum total of 100% (2011)","No","No","code: http://qcode.us/codes/napa/","mobile home: 6-66.040","density bonus: 17.52.130","housing impact fee: 17.47","SRO: 17.52.460","","",""],

["54","Newark","83","650916","Alameda","No","No","No","No","No","No","No","No","imposed on all developers of residential and nonresidential development project (2014)","No","Min. 15% of units to be affordable. Rental: 40% of those affordable units shall be affordable to very low, 40% to low, and 20% to moderate income households. For-sale: 15% of those affordable units shall be affordable to low income households and 85% to moderate income households. Yes in-lieu fee. (2004)","No","No","Yes","code: https://www.municode.com/library/ca/newark/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=CD_ORD_TIT17ZO_CH17.18AFHOPR","housing impact fee: 17.18.030","","","","","",""],

["55","Novato","47","652582","Marin","No","No","No","100% of % increase in CPI (2004)","Yes - Housing Element Policy 7.2 (2015-2023)","Vacancy rate in City must be above 4.5%.","Yes","No","No","No","Affordable housing opportunity overlay district. 20% must be inclusionary. One half of the required number of affordable units must be affordable to low income households and one half must be affordable to moderate income households. Yes in-lieu fee. (1997, amended 2013)","No","No","No","code: https://www.municode.com/library/ca/novato/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22subdivision%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=CHXIXZO_ART2ZODIALLAUSZOECST_DIV19.16OVZODI_19.16.070AFHOOPAHOVDI&showChanges=true","Condomium conversion: Ord. No. 750, § 9.13.006; Ord. No. 1127, §§ 13, 14","inclusionary: 19.16.070","mobile home: 20-5; Ord. No. 1371, § 1; Ord. No. 1411, § 1; Ord. No. 1475, § 1","","","",""],

["56","Oakland","69","653000","Alameda","Yes (2002)","One increase per year, 2% (2003), adjusted to CPI (2002) rent adjustment program; 2015-2016: 1.7% CPI rate for rent increase. ","Housing Residential Rent-Relocation Board (1999)","Automatic 5% increase allowed (1980)","Yes","Yes, including tenant assistance program (1992); must reserve units - 15% for low income and 33% for moderate income for 20 years (2014)","Yes","Yes (2002): (number of gross square feet in the development project devoted to office or warehouse/distribution uses minus 25,000 square feet) times $4.00 equals the amount of the fee","Office and warehouse $4.56/sf. Funds go to the Affordable Housing Trust Fund (2005)","Yes","No","No","Yes (2004)","Yes","code: https://www.municode.com/library/ca/oakland/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT16SU_CH16.36COCO","Condominium conversion: 16.36 & 17.117.070","rent review board: http://www2.oaklandnet.com/Government/o/hcd/o/RentAdjustment/","housing impact fee: 15.68","","","",""],

["57","Oakley","101","653070","Contra Costa","No","No","No","No","Yes -  Located exclusively in the General Commercial (C) Zone District","No","Yes","No","No","No","Min. 10% affordable to low- or moderate-income households. At least 40% of these affordable housing units must be available to and occupied by very low-income  households. Yes in-lieu fee. (1999)","No","No","No","Code: http://www.codepublishing.com/ca/oakley/","SRO: 9.1.1218","","","","","",""],

["58","Orinda","71","654232","Contra Costa","No","No","No","No","No","rent must not be raised more than 100% of CPI; moving assistance; improvements required; at least 10% discount for tenants","No","No","No","No","No","No","No","No","code: https://www.municode.com/library/ca/orinda/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT16SU_CH16.84COCO","Condominium conversion: CCCC§§ 926-16.202 — 926-16.206","","","","","",""],

["59","Pacifica","33","654806","San Mateo","No","No","No","75% of CPI (1991)","No","Vacancy rate in the City must be above 5%. Inclusionary requirement: 40% to low and moderate income, 20% to low income. Sales price must be less than 2.5 times the annual median income for low or moderate income households. Includes relocation assistance and tenant's discounts. Year: 1982, amended 1984","No","No","No","No","15% of units to be BMR. Yes in-lieu fee. (2007)","No","No","No","https://www.municode.com/library/ca/pacifica/codes/","Condominium conversion: 24.5","BMR: Sec 9-4.470","mobile home: sec 9-1.203","desnity bonus: sec 9-4.4102","","",""],

["60","Palo Alto","17","655282","Santa Clara","No","No","Palo Alto's Mediation Ordinance- mediation only (2002)","No","No","Vacancy rates are considered or 1:2 ratio for below-market-rate unit to non-below-market unit AND at least 2/3 tenants consent to conversion. Year: 1979, amended 1981.","No","Yes (1984)","Commercial uses $4.03/sf.  20,000 sf exemption. (1984)","Yes","15-20% affordable units. Yes in-lieu fees. (2008)","No","Yes (South County Housing)","No","Code: http://library.amlegal.com/nxt/gateway.dll/California/paloalto_ca/paloaltomunicipalcode?f=templates$fn=default.htm$3.0$vid=amlegal:paloalto_ca","Condominium conversion: Chapter 21.40","rent control: http://library.amlegal.com/nxt/gateway.dll/California/paloalto_ca/paloaltomunicipalcode?f=templates$fn=default.htm$3.0$vid=amlegal:paloalto_ca","BMR: 18.14.030","http://www.paloaltomediation.com/documents/PaloAltoTenantGuide.pdf","","",""],

["61","Petaluma","58","656784","Sonoma","No","No","No","100% of CPI or 6% cap (1994)","No","Vacancy rate in the City must be above 3%, or if one-for-one replacement of rental units of a similar type occurs, or if two-thirds of the adult tenants agree to the conversions in the city. In April and November of each year, the director of planning shall determine the vacancy rate and the vacancy surplus:  40% of the vacancy must be greater than or equal to the total number of rental apartments in the proposal. Year: 1978, amended 1982.","Yes","Yes (2003)","No","Yes","15% affordable to low- and moderate-income households. Yes in-lieu fee. (2012)","No","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","Housing trust fund: http://housingtrustfundproject.org/wp-content/uploads/2013/09/City-htfund-revenue-sources-final-wodollars-2013.pdf","http://www.codepublishing.com/ca/petaluma.html","condomium conversion: Chapter 20.30; mobile home 6.50.040; Inclusionary housing: 20.80.050","","","","",""],

["62","Piedmont","57","656938","Alameda","No","No","No","No","No","Apartments converted to condominiums must be replaced in kind by an equivalent number of equivalently priced rental units. Rent restricted for 55 years (Amended 2005)","No","No","No","No","No","No","No","No","code: http://www.ci.piedmont.ca.us/citycode.shtml","condominium conversion: Sec 19.62","","","","","",""],

["63","Pinole","72","657288","Contra Costa","No","No","No","No","No","Vacancy rate in City must be above 5% (2010)","Yes","No","No","No","Min. 15% of units to be affordable and of these, 40% must be affordable to very low-income households. Yes in-lieu fee. (2010)","No","No","No","code: http://library.amlegal.com/nxt/gateway.dll/California/pinole_ca/pinolecamunicipalcode?f=templates$fn=default.htm$3.0$vid=amlegal:pinole_ca","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/pinole_5th_draft091914.pdf","condominium conversion: 17.60.060","affordable housing: 17.32.010","","","",""],

["64","Pittsburg","96","657456","Contra Costa","No","No","No","No","No","Max # is established by the city council at the beginning of each year. Vacancy rates are considered. Relocation assistance; restricted annual rent increase for low and moderate income households. Year:  1989, amended 1993, 2009.","No","No","No","No","Rental: 6% affordable to very low-income households and 9% affordable to low-income households; or 10% affordable to very low-income rent units; or  6% affordable to extremely low-income renter units. For-sale: 9% affordable to low-income households and 6% affordable to very low-income households; or 20% affordable to low-income households (2004, amended 2007)","No","No","No","code: http://www.ci.pittsburg.ca.us/index.aspx?page=439","condominium conversion: 17.44","inclusionary: 18.86.040","","","","",""],

["65","Pleasant Hill","97","657764","Contra Costa","No","No","No","No","Yes - SRO facility may be proposed and approved in the multifamily, retail business and professional and administrative office zoning districts","Vacancy rate in City must be above 5%; tenant relocation plan; improvements required;  total city housing stock must be above 20% . (1991, amended 2000, 2005, 2007)","No","No","No","No","5% affordable to very low- and 10% affordable to low-income households. Yes in-lieu fee. (1996, amended in 2004 and 2005)","No","No","No","http://www.codepublishing.com/CA/pleasanthill.html","SRO: 18.20.085","","","","","",""],

["66","Pleasanton","50","657792","Alameda","No","No","No","100% of CPI of 5% cap (1993)","No","Yes. Year: 1983","Yes","Yes (1978)","Yes since 1990, $.4/ft2, including inflation provision, reset in 2003 to 2.28 and currently $2.87 (1990)","No","For projects of 15 units or more, 15% to very low and low; min. 20% affordable to very low, low, and/or moderate income households. Yes on in-lieu fees. (2000)","No","No","Yes","http://qcode.us/codes/pleasanton/","Condominium: Title 19","","","","","",""],

["67","Portola Valley","38","658380","San Mateo","No","No","No","No","No","No","No","No","No","No","For projects of 7 or more units, 15% affordable units. Yes in-lieu fee. (1991, amended 1997); Ad-Hoc Affordable Housing Committee (2013)","No","No","No","code: https://www.municode.com/library/ca/portola_valley/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22relocation%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT17SU_CH17.04GEPR_17.04.110SUCOES","","","","","","",""],

["68","Redwood City","65","660102","San Mateo","No","No","No","No","No","No","Yes","Yes (2015) - not codified yet","No","No","No","No","No","No","http://www.mercurynews.com/breaking-news/ci_29029210/redwood-city-council-approves-affordable-housing-impact-fee","","","","","","",""],

["69","Richmond","73","660620","Contra Costa","No","No","No","No","Because SROs typically have unusual site development features or operating characteristics that require special consideration, they are not allowed as a matter of right. SROs are conditionally permitted in the MFR-2, MFR-3, MFR-4, C-1, C-2, C-3, C-B, and C-C zoning districts. No other changes related to SRO units are anticipated as part of the comprehensive update to the City’s Zoning Ordinance that is currently underway.","No","Yes","No","No","No","17% affordable to moderate-income households; or 15% affordable to low-income households; or  10% affordable to very-low-income households; or min. 12.5% available to a combination of very low and low-income households including at least two affordable to very low-income  households. Yes in-lieu fee. (2001)","No","Yes (NCLT)","Yes","","","","","","","",""],

["70","Rio Vista","5","660984","Solano","No","No","No","No","No","No","No","No","No","No","No","No","No","No","code: http://qcode.us/codes/riovista/","condominium conversion: 16.40","","","","","",""],

["71","Rohnert Park","7","662546","Sonoma","No","No","No","75% of CPI or 4% cap (1987); rent appeals board","No","No","No","Yes - Affordable Housing linkage fee for nonresidential developments (2006)","Yes- uses include, but are not limited to, assistance to housing development corporations, equity participation loans, grants, predevelopment loan funds, participation leases, loans to develop affordable housing or other public/private partnership arrangements (2006)","No","15% affordable to low-  and moderate-income households. Yes in-lieu fee. (2003)","No","No","Yes, at Sonoma Mountain Village","code: https://www.municode.com/library/ca/rohnert_park/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22housing%20impact%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT3REFI_CH3.36AFHOLIFE_3.36.010PU","ordinance changes: http://www.ci.rohnert-park.ca.us/index.aspx?page=958","mobile home: 9.70.030","housing impact fee: 3.36.030","","","",""],

["72","Ross","21","662980","Marin","No","No","No","No","No","No","No","No","No","No","No","No","No","No","code: http://www.townofross.org/administration/page/municipal-code","","","","","","",""],

["73","San Anselmo","22","664434","Marin","No","No","No","No","No","Yes - Conversion only allowed when the Town’s proportion of multi-family rental units (exclusive of second units) is 25% or more of the total housing stock, or above 20% AND at least 3/4 tenants consent to conversion. Year: 1980","No","No","No","No","15% affordable to very low, low, and moderate income households. Yes in-lieu fee. (1995)","No","No","No","https://www.municode.com/library/ca/san_anselmo/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22condominium%20conversion%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT10PLZO_CH7COCO","Condomium conversion: 10-chapter 7","","","","","",""],

["74","San Bruno","19","665028","San Mateo","No","No","No","No","No","Yes - Only if conversion will not cause the number of multiple family rental units in the city to be less than the minimum established as a goal or policy in the housing element. Year: amended 1982. ","Yes","No","No","No","For projects of 10 units or more, 15% must be BMR units. Rental: 40% of BMR units shall be restricted to very low-income households, 60% shall be restricted to low-income households. For sale: 40% of BMR units shall be restricted to low-income households, 60% shall be restricted to moderate-income households (2008)","No","No","No","http://qcode.us/codes/sanbruno/","Density bonus: 12.250","BMR: 12.230.030","","","","",""],

["75","San Carlos","54","665070","San Mateo","Yes in conversion projects (2011)","No","No","No","Yes - Policy HOU-7.2 ","relocation assistance; tenant protections; improvements required (2011)","No","Yes (2011)","No","No","For-sale: min. 15% of total units shall be BMR units restricted for sale to and occupancy by moderate- and low-income households. Rental: 15% of the total units shall be BMR units, of which 5% shall be affordable to low-income households and 10% to very low-income households (2004, amended 2015)","No","No","No","code: http://www.codepublishing.com/ca/sancarlos/#!/SanCarlos18/SanCarlos1816.html","Condominium Conversion: http://www.codepublishing.com/ca/sancarlos/html/sancarlos17/sancarlos1748.html","housing impact fee & inculsionary housing: 18.16","housing element: http://www.cityofsancarlos.org/civicax/filebank/blobdload.aspx?blobid=5972","","","",""],

["76","San Francisco","35","667000","San Francisco","Yes","60% of CPI with maximum of 7% (1987, last codified 2010).","Yes- arbitration only on matters that are part of the Rent Ordinance","60% of CPI or 4-7% cap (1970)","Yes (Central City SRO Collaborative)","Only 200 units annually may be converted. Year: 1981, last amended 2015","No","Yes (1997)","Office space $11.34/sf, Entertainment $10.57/sf, Hotel $8.50/sf, Research and development $7.55/sf, Retail $10.57/sf for developments greater than 25,000 square feet. All funds go to the Affordable Housing Fund (1981 est. as policy, 1985 as ordinance, 2001 fees increase)","Yes (prop C)","12% of their units on-site or 20% of their units off-site as affordable to low- to moderate-income households. Yes in-lieu fee. (1992)","No","Yes (2001)","Yes (1998, last modified 2006)","http://library.amlegal.com/nxt/gateway.dll?f=templates&fn=default.htm&vid=amlegal:sanfrancisco_ca","Rent stablization: ch 37","condo: art 9","Housing trust fund: http://www.sfhac.org/policy-advocacy/affordable-housing-trust-fund/","","","",""],

["77","San Jose","18","668000","Santa Clara","No","8% annual increase; 21% if the last increase was more than 24 months ago (1979, last amended 2003).","Advisory Committee on Rents","75% of CPI or 3-7% cap (1985)","No","No","Yes","Yes (2014)","No","Yes (NCLT)","For-sale: 15% affordable housing units. Rental: 9% affordable housing units 6% affordable to very low-income households; yes in-lieu fee","No","Yes (South County Housing)","No","Code: https://www.municode.com/library/ca/san_jose/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CInclusionary%20housing%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT5HO_CH5.08INHO_PT7IMWAEN_5.08.730IMEN","Inclusionary housing: 5.08.400","","","","","",""],

["78","San Leandro","84","668084","Alameda","No","No","Yes- mediation only (2001)","No","No","Considers vacancy rate and rehab to meet current building standards (2001)","No","No","No","No","15%  affordable units and of these, 40% must be set aside for very low-income households. Yes in-lieu fee. (2004)","No","No","No","code: http://qcode.us/codes/sanleandro/","housing element: http://www.sanleandro.org/civicax/filebank/blobdload.aspx?BlobID=23216","","","","","",""],

["79","San Mateo","37","668252","San Mateo","No","No","No","No","No","Yes, including relocation assistance. Year: 1979, amended 1981 and 1983","Yes","Yes (2010)","No","No","For projects of 11 units or more, 15% of ownership units to moderate income families, or 10% of ownership units to low income families. 15% of rental units to low income families, or 10% of rental units  to very low income families. (Last amended 2011)","No","No","No","http://qcode.us/codes/sanmateo/","Condomium conversion: Title 26.65","","BMR: http://www.cityofsanmateo.org/index.aspx?NID=1095","","","",""],

["80","San Pablo","74","668294","Contra Costa","No","No","No","No","Yes","Conversions may only be 3% of the total rental stock, and vacancy rate in City must be above 5%. Includes tenant protection and assistance provisions and homeownership assistance. Year: 1980, ameded 1981.","Yes","No","No","No","15% affordable to very low- and low- income households. Yes in-lieu fee.","Yes (2006) -additional bonus for each 1% increase in target units","No","Yes","http://www.codepublishing.com/ca/sanpablo/","Condomium conversion: 15.44","Density bonus: 17.34","sro: http://www.ci.san-pablo.ca.us/DocumentCenter/View/4936","","","",""],

["81","San Rafael","66","668364","Marin","No","No","No","Yes (2014)","Yes","Vacancy rate in City must be above 5% (2002)","No","No","No","No","For projects of 2-10 housing units, 10% shall be BMR units. For projects of 11-20 housing units, 15% shall be BMR units. For projects of 21+ units, 20% shall be BMR units. Rental: 50% of BMR units affordable to very low income households and the rest to low income households. For-sale:  50% of BMR units affordable to low income households and the rest to moderate income households. Yes in-lieu fee. (Amended 2001)","No","Yes (NCLT)","No","","","","","","","",""],

["82","San Ramon","98","668378","Contra Costa","No","No","City Housing Authority- mediator and work towards affordable housing goals","No","Yes - amended the Zoning Ordinance to facilitate the provision of SROs consistent with SB 2 enacted in 2007.","Yes  (2008)","Yes","No","Yes (2009)","No","For projects with more than 10 units, 25% of total units must be BMR. Yes in-lieu fees. (not a policy, but negotiated like an exaction)","Yes- for senior citizen housing developments (Updated 2006)","No","No","code: https://www.municode.com/library/ca/san_ramon/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22inclusionary%20housing%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TITCCODELAUS_DIVC5SUPR_CHVIICOCO_C5-100GERE","housing element: http://www.ci.san-ramon.ca.us/gprc/documents/11Housing.pdf","","","","","",""],

["83","Santa Clara","43","669084","Santa Clara","No","No","No","No","No","Yes - restricts when rentals become less than 40% of housing stock. Other requirements: frontage improvements; storm drainage; sanitary sewers; water supply; utilities; energy conservation; opportunity to install cable television service; security improvement. Year: 1983","No","No","No","No","No","No","Yes (South County Housing)","No","http://www.codepublishing.com/CA/SantaClara/#!/SantaClara18/SantaClara1878.html","Condominium: Ch. 17.05; Residential density: 18.78 ","","","","","",""],

["84","Santa Rosa","59","670098","Sonoma","No","No","No","100% of CPI or 6% cap (2004)","Yes","Yes; housing impact considered; energy coservation required; subdivision committee. Year: 1987, amended 1996, 1998","Yes","Yes but could  allocate units on-site instead (2012)","No","Yes","15% affordable to low- income households. Yes on in-lieu fees. (1993, last amended 2012)","No","Yes, Partnered w/ Housing Land Trust of Sonoma County","No","code: http://ci.santa-rosa.ca.us/departments/cityadmin/cityclerk/Pages/CityCode.aspx","condominium conversion: title 19","mobile home: title 6 ch 6-66","housing impact fee: 15.94","SRO: 20-42.164","","",""],

["85","Saratoga","12","670280","Santa Clara","No","No","No","No","Yes - permitted in C-N(RHD) Districts","Vacancy rate in City must be above 3% (Amended 2003)","No","No","No","No","No","No","Yes (South County Housing)","No","code: https://www.municode.com/library/ca/saratoga/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%E2%80%9CCondominium%20conversion%E2%80%9D%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=CH14SU_ART14-75COCO","condominium conversion: 14-75.020","housing element: http://www.saratoga.ca.us/civicax/filebank/blobdload.aspx?BlobID=3497","","","","",""],

["86","Sausalito","70","670364","Marin","No","No","No","No","Yes - allow single room occupancy facilities as a commercial use (2014)","Vacancy rate in City must be above 5% (2003)","No","No","No","No","No","No","No","No","code: http://www.codepublishing.com/ca/sausalito/","condominium conversion: 10.66.140","SRO:  Ordinance No. 1223","","","","",""],

["87","Sebastopol","8","670770","Sonoma","No","No","No","100% of CPI (1992)","No","Yes (2005); relocation assistance","No","No","No","No","For projects of 3 or more, 20% affordable to very  low- or low- income households. Yes in-lieu fee. (1994, last revised 2003)","Yes - as part of its inclusionary policy (1994)","No","No","zoning ordinanace: http://ci.sebastopol.ca.us/sites/default/files/rmansour/zoning_ordinance_related_land_use_ordinances_adopted_june_2015.pdf","inclusionary housing: 17.240.040","mobile home: 17.93","","","","",""],

["88","Sonoma","9","672646","Sonoma","No","No","No","No","No","Yes (2003)","No","Yes (2005)","No","No","20% affordable to low- and moderate- income households (2003, last amended 2014)","No","No","No","code: http://www.codepublishing.com/CA/Sonoma/","housing element: http://www.sonomacity.org/Sonoma/media/Files/planning/HE_Final.pdf","","","","","",""],

["89","South San Francisco","55","673262","San Mateo","No","No","No","No","Yes","Vacancy rate in City must be above 5%. Plus, there is an annual limitation determined each year. House replacement fee of $5,000 or 5% of the purchase price. Year: 1982","Yes","No","No","No","For projects of 4 or more,  20% affordable to low- and moderate- income households. Yes in-lieu fee. (2010)","No","No","No","http://qcode.us/codes/southsanfrancisco/","condominium: 19.80.030","zoning: 20.380.003","","","","",""],

["90","St. Helena","88","664140","Napa","No","No","No","No","Yes - allow single room occupancy housing as a permitted use in the High Density Residential district","Vacancy rates are considered when reviewing permit applications. (1994)","Yes","Yes","Yes (2004)","Yes","25% affordable units. Yes in lieu-fee for developments of 4 or fewer units. (2004)","No","No","No","code: http://www.codepublishing.com/CA/StHelena/#!/StHelena17/StHelena17146.html#17.146.030","housing trust fund: 17.146.030","housing impact fee: 17.146.040","inclusionary housing: housing element","SRO: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/saint-helena-5th-draft030315.pdf","SRO http://cityofsthelena.org/sites/default/files/zota_he_sr_packet_ready.pdf","",""],

["91","Suisun City","6","675630","Solano","No","No","No","No","Yes -  Assembly Bill (AB) 2634 - explicitly allowed in the City’s Zoning Ordinance  ","No","No","No","No","No","No","No","No","No","","housing element: http://www.suisun.com/wp-content/files/Suisun_City_Housing_Element_Final_Draft.pdf?bcsi_scan_2687365ababd2c82=0&bcsi_scan_filename=Suisun_City_Housing_Element_Final_Draft.pdf","","","","","",""],

["92","Sunnyvale","40","677000","Santa Clara","No","No","No","No","No","Section 19.70 of the Zoning Code- prohibits conversion unless the vacancy rate for rental housing exceeds 3 percent for one year (1984, amended 1999)","Yes","No","Industrial development $7.19/sf. Fee charged only if development exceeds the 35% floor area ratio. Fees go toward funding low and moderate income housing (1984)","No","Rental: 15% affordable to moderate- and/or low-income households. For-sale: 12.5% affordable to moderate- and/or low-income households. (BMR Program 1980-2009, amended 2012)","Yes","Yes (South County Housing)","No","code: http://qcode.us/codes/sunnyvale/","","","","","","",""],

["93","Tiburon","24","678666","Marin","No","No","No","No","No","Vacancy rate in City must be above 4.5% for a conversion to be allowed. Year: 1974","No","No","No","No","3-6 new lots or dwelling units: 15% affordable units; 7-12 new lots or dwelling units: 15% affordable units to very low, low, or moderate-income households in perpetuity, 5% to very low- or low-income households; more than 12 new lots or dwelling units: 20% affordable units to very low, low, or moderate-income households in perpetuity, 5% to very low- or low-income households; Yes in-lieu fee (2010)","Yes- for residential developments located within an affordable housing overlay zone (2010)","No","No","Inclusionary housing and density bonuses: https://www.municode.com/library/ca/tiburon/codes/code_of_ordinances?nodeId=TITIVLAIMUS_CH16ZO_16-70INHODEBO_16-70.010PU","","","","","","",""],

["94","Union City","85","681204","Alameda","No","No","No","90% of CPI or 7% cap (1980, amended last in 2001)","No","Yes, including a relocation assistance plan. Year: 1980","No","Yes (1999, last ameneded in 2006)","No","No","Min. 15% of units to be affordable. Rental: 30% of those affordable units shall be affordable to very low- and 70% to low- income households. For-sale: 10% of those affordable units shall be affordable to low -income households, 90% to moderate-income households.  Yes in-lieu fees. (2002, amended 2006)","No","No","No","http://qcode.us/codes/unioncity/","Condomium conversion: 17.84","mobile home: Title 16.40","housing impact fee: 18.105","BMR: 18.33","","",""],

["95","Vacaville","68","681554","Solano","No","No","No","Graduated CPI (1992)","No","Vacancy rate in City must be above 3%. Other requirements: metering; off-street parking; sound insulation; common and private recreational open space. Year: 1982","Yes","No","No","No","No","No","No","No","http://www.codepublishing.com/ca/vacaville/","Condominium conversion: CH 14.11.164; Density Bonus: 14.09.116","mobie home: ch 2.36","","","","",""],

["96","Vallejo","39","681666","Solano","No","No","No","5% cap (1982); must not exceed CPI % increase (2004)","No","No","Yes","No","No","No","No","No","No","Yes","code: https://www.municode.com/library/ca/vallejo/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22mobile%20home%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TIT5BULIRE_CH5.64MOHORERE_5.64.080EXREIN","mobile home: 5.64.076","","","","","",""],

["97","Walnut Creek","99","683346","Contra Costa","No","No","No","No","No","Requires major rehab (1984, last amended 2011); improvements required; tenant's right to Purchase; restricted rent increase; Vacancy rate in City must be above 5% (1982)","Yes","Yes (2005)","$5 per square foot (2005)","No","For projects of 10 or more units: Rental: all projects must pay an Affordable Housing Impact Fee. For-sale: 6% of units must be affordable to very low income households, 7% to low, and 9% to moderate income housing or pay  in-lieu fees. (2004, amended 2009, 2010, 2011)","No","No","No","code: http://www.codepublishing.com/CA/WalnutCreek/#!/WalnutCreek10/WalnutCreek1001.html#10-1.702","Condomium conversion: Article 7 & 8","","","","","",""],

["98","Windsor","77","685922","Sonoma","No","No","No","100% of CPI or 6% cap (1992)","No","No","No","No","No","No","Set aside either 10% of units for very low-income households; or 15% for low-; or 20% for moderate.  Yes in-lieu fee. (2004, last amended 2008) Station Area/Downtown Inclusionary Housing Ordinance (2016)","No","No","No","code: https://www.municode.com/library/ca/windsor/codes/code_of_ordinances?searchRequest=%7B%22searchText%22:%22%5C%22affordable%20housing%5C%22%22,%22pageNum%22:1,%22resultsPerPage%22:25,%22booleanSearch%22:false,%22stemming%22:true,%22fuzzy%22:false,%22synonym%22:false,%22contentTypes%22:%5B%22CODES%22,%22ORDINANCES%22%5D,%22productIds%22:%5B%5D%7D&nodeId=TITXVIDEAGSUFEDESEZOGRMA_CH8SUOR_ART12VETEMA_16-8-1225FIPR","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/windsor_5th_draft092214.pdf?bcsi_scan_2687365ababd2c82=lzDRNjbuSlF/IyGImZl5aOr251AFAAAAuFpqGA==&bcsi_scan_filename=windsor_5th_draft092214.pdf","","","","","",""],

["99","Woodside","56","686440","San Mateo","No","No","No","No","No","No","No","No","No","No","No","No","No","No","code: http://library.amlegal.com/nxt/gateway.dll/California/woodside_ca/woodsidecaliforniacodeofordinances?f=templates$fn=default.htm$3.0$vid=amlegal:woodside_ca","","","","","","",""],

["100","Yountville","91","686930","Napa","No","No","No","No","Yes - Flexibility will also be provided to consider SRO housing for commercial developments","Vacancy rate in City must be above 5% or rental units in the town above 35% of the total housing stock (Amended 1994)","Yes","No","Yes (1992)","No","15% affordable units for five or more units. Yes in-lieu fee. (1992, Amended 2012)","No","No","No","code: http://qcode.us/codes/yountville/","housing element: http://www.hcd.ca.gov/housing-policy-development/housing-resource-center/plan/he/housing-element-documents/yountville-5th-adopted020915.pdf","","","","","",""]]
*/